Document: forest
Title: Debian forest Manual
Author: <insert document author here>
Abstract: This manual describes what forest is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/forest/forest.sgml.gz

Format: postscript
Files: /usr/share/doc/forest/forest.ps.gz

Format: text
Files: /usr/share/doc/forest/forest.text.gz

Format: HTML
Index: /usr/share/doc/forest/html/index.html
Files: /usr/share/doc/forest/html/*.html
