add_subdirectory(batterymonitor)
add_subdirectory(mainmenu)
add_subdirectory(clock)
add_subdirectory(nmcontrol)
add_subdirectory(volume)
add_subdirectory(cpumonitor)
add_subdirectory(memorymonitor)
add_subdirectory(sensors)
add_subdirectory(windowlist)
add_subdirectory(quicklaunch)
add_subdirectory(systray)
add_subdirectory(deskswitch)
